// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Entity struct {
	FindUserByID     *User    `json:"findUserByID"`
	FindProductByUpc *Product `json:"findProductByUpc"`
}

type Product struct {
	Upc     string    `json:"upc"`
	Reviews []*Review `json:"reviews"`
}

func (Product) Is_Entity() {}

type Review struct {
	Body    string   `json:"body"`
	Author  *User    `json:"author"`
	Product *Product `json:"product"`
}

type User struct {
	ID      string    `json:"id"`
	Reviews []*Review `json:"reviews"`
}

func (User) Is_Entity() {}
